project:
  type: website
  output-dir: docs

website:
  title: "Mindy's Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - labs.qmd
      - project.qmd
      - presentation.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

